package com.pawlink.capture;
import android.app.*;
import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.lang.reflect.*;
import java.util.concurrent.atomic.*;
import org.json.*;

/** Uses an isolated synthetic recording; never edits existing collection sessions. */
final class ReviewFlowCheck {
    static void require(boolean ok,String reason){if(!ok)throw new AssertionError(reason);}
    static Object field(Object object,String name)throws Exception{Field f=object.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(object);}
    static Object main(Instrumentation i,java.util.concurrent.Callable<Object> call){AtomicReference<Object> result=new AtomicReference<>();AtomicReference<Throwable> failure=new AtomicReference<>();i.runOnMainSync(()->{try{result.set(call.call());}catch(Throwable t){failure.set(t);}});if(failure.get()!=null)throw new RuntimeException(failure.get());return result.get();}
    static void waitFor(Instrumentation i,java.util.concurrent.Callable<Object> condition,String reason){long until=SystemClock.uptimeMillis()+10000;while(SystemClock.uptimeMillis()<until){if(Boolean.TRUE.equals(main(i,condition)))return;SystemClock.sleep(100);}throw new AssertionError(reason);}
    static ReviewActivity open(Instrumentation i,String name){Intent intent=new Intent(i.getTargetContext(),ReviewActivity.class);intent.putExtra(ReviewActivity.EXTRA_SESSION_NAME,name);intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);ReviewActivity activity=(ReviewActivity)i.startActivitySync(intent);i.runOnMainSync(()->activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON));return activity;}
    private static void saveScreenshot(Instrumentation i,String name)throws Exception{android.graphics.Bitmap image=i.getUiAutomation().takeScreenshot();require(image!=null,"screenshot capture");try(OutputStream out=new FileOutputStream(new File(i.getTargetContext().getCacheDir(),name))){image.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}image.recycle();}
    static void run(Instrumentation i)throws Exception{
        String name="session-ui-check-"+System.currentTimeMillis();File dir=new File(new File(i.getTargetContext().getExternalFilesDir(null),"sessions"),name);require(dir.mkdirs(),"create fixture");
        try(InputStream in=i.getContext().getAssets().open("review-test/timeline.mp4");OutputStream out=new FileOutputStream(new File(dir,"video.mp4"))){byte[] buffer=new byte[32768];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);}
        long origin=10_000_000_000L;
        JSONObject manifest=new JSONObject();manifest.put("schema_version",3);manifest.put("started_elapsed_ns",origin);manifest.put("video_started_elapsed_ns",origin);manifest.put("capture_mode","hand_test");try(FileWriter w=new FileWriter(new File(dir,"manifest.json"))){w.write(manifest.toString());}
        try(PrintWriter w=new PrintWriter(new File(dir,"imu.csv"))){w.println("host_time_ns,elapsed_time_ns,device_time_ms,sequence,label,label_source,ax_g,ay_g,az_g,gx_dps,gy_dps,gz_dps,epoch");for(int n=0;n<700;n++){int ms=n*20;boolean active=ms>=2000&&ms<3000||ms>=6000&&ms<7000||ms>=10000&&ms<11000;w.println("0,"+(origin+ms*1_000_000L)+","+ms+","+n+",unknown,system,0,0,1,0,"+(active?80:0)+",0,1");}}
        try(PrintWriter w=new PrintWriter(new File(dir,"sync.csv"))){w.println("epoch,t1_host_ns,t2_device_ms,t3_device_ms,t4_host_ns");for(int n=0;n<5;n++){int ms=500+n*100;long h=origin+ms*1_000_000L;w.println("1,"+(h-3000000)+","+ms+","+ms+","+(h+3000000));}}
        ReviewActivity a=open(i,name);final ReviewActivity first=a;waitFor(i,()->field(first,"loaded"),"load review");
        main(i,()->{require((int)field(first,"candidateIndex")==0,"auto first candidate");require((int)field(first,"rangeStart")==2000&&(int)field(first,"rangeEnd")==3000,"select actual IMU interval");require((int)field(first,"previewStart")==0&&(int)field(first,"previewEnd")==5000,"two-second context without changing labels");require((boolean)field(first,"playing"),"automatic preview");((Spinner)field(first,"label")).setSelection(2);((Button)field(first,"confirm")).performClick();return null;});
        waitFor(i,()->(int)field(first,"candidateIndex")==1&&!(boolean)field(first,"busy"),"save and advance");
        JSONObject saved=new JSONObject(new String(java.nio.file.Files.readAllBytes(new File(dir,"review-v3.json").toPath()),java.nio.charset.StandardCharsets.UTF_8));JSONObject segment=saved.getJSONArray("segments").getJSONObject(0);require(segment.getInt("start_video_ms")==2000&&segment.getInt("end_video_ms")==3000,"persist without context padding");require(segment.getString("label").equals("translation_test"),"persist chosen behavior");
        main(i,()->{((Button)field(first,"skip")).performClick();return null;});waitFor(i,()->(int)field(first,"candidateIndex")==2&&!(boolean)field(first,"busy"),"skip and advance");
        main(i,()->{Method undo=ReviewActivity.class.getDeclaredMethod("undo");undo.setAccessible(true);undo.invoke(first);return null;});waitFor(i,()->!(boolean)field(first,"busy"),"undo save");saved=new JSONObject(new String(java.nio.file.Files.readAllBytes(new File(dir,"review-v3.json").toPath()),java.nio.charset.StandardCharsets.UTF_8));require(saved.getJSONArray("skipped_candidate_ids").length()==0,"undo skip decision");
        main(i,()->{first.finish();return null;});i.waitForIdleSync();a=open(i,name);final ReviewActivity reopened=a;waitFor(i,()->field(reopened,"loaded"),"reopen review");main(i,()->{require((int)field(reopened,"candidateIndex")==1,"resume first pending candidate");require((int)field(reopened,"previewStart")==4000&&(int)field(reopened,"previewEnd")==9000,"resume context");require(!((EditText)field(reopened,"startInput")).isShown(),"hide millisecond fields");require(!((Spinner)field(reopened,"reason")).isShown(),"hide technical exclusion menu");return null;});
        waitFor(i,()->field(reopened,"playbackPlayer")!=null&&!((boolean)field(reopened,"seekingPlayback")),"player prepared and positioned");
        main(i,()->{if((boolean)field(reopened,"playing"))((Button)field(reopened,"play")).performClick();((Button)field(reopened,"play")).performClick();require((int)field(reopened,"playStart")==6000&&(int)field(reopened,"playEnd")==7000,"main button plays selected range");return null;});
        waitFor(i,()->!(boolean)field(reopened,"seekingPlayback")&&((VideoView)field(reopened,"video")).getCurrentPosition()>=6000,"actual playback seeks to selection instead of zero");
        for(int tick=0;tick<18;tick++){main(i,()->{int position=((VideoView)field(reopened,"video")).getCurrentPosition();require(position>=5950&&position<7100,"selected playback remains inside interval across loop: "+position);return null;});SystemClock.sleep(100);}
        main(i,()->{Method begin=ReviewActivity.class.getDeclaredMethod("beginPlayback",int.class,int.class,boolean.class);begin.setAccessible(true);begin.invoke(reopened,0,(int)field(reopened,"durationMs"),false);require(!(boolean)field(reopened,"loop"),"full video does not loop");require((int)field(reopened,"rangeStart")==6000&&(int)field(reopened,"rangeEnd")==7000,"full playback preserves labels");return null;});
        waitFor(i,()->!(boolean)field(reopened,"seekingPlayback")&&((VideoView)field(reopened,"video")).getCurrentPosition()<1000,"full video plays from zero");
        main(i,()->{((android.media.MediaPlayer)field(reopened,"playbackPlayer")).seekTo((long)(int)field(reopened,"durationMs")-300,android.media.MediaPlayer.SEEK_CLOSEST);return null;});
        waitFor(i,()->!(boolean)field(reopened,"playing"),"full playback stops at end");
        main(i,()->{Method expand=ReviewActivity.class.getDeclaredMethod("expandPreview",int.class);expand.setAccessible(true);expand.invoke(reopened,1);require((int)field(reopened,"previewEnd")==11000,"extend following context");require((int)field(reopened,"rangeStart")==6000&&(int)field(reopened,"rangeEnd")==7000,"context expansion preserves annotation");ImuTimeline t=(ImuTimeline)field(reopened,"timeline");long now=SystemClock.uptimeMillis();float x=t.getWidth()*2f/7f,y=40;t.dispatchTouchEvent(MotionEvent.obtain(now,now,MotionEvent.ACTION_DOWN,x,y,0));t.dispatchTouchEvent(MotionEvent.obtain(now,now+20,MotionEvent.ACTION_MOVE,t.getWidth()*1.5f/7f,y,0));t.dispatchTouchEvent(MotionEvent.obtain(now,now+40,MotionEvent.ACTION_UP,t.getWidth()*1.5f/7f,y,0));require(Math.abs((int)field(reopened,"rangeStart")-5500)<5,"drag start into earlier context");require((int)field(reopened,"rangeEnd")==7000,"drag preserves end boundary");return null;});
        main(i,()->{require(((TextView)field(reopened,"annotationStatus")).getText().toString().contains("待标注"),"pending status visible");Field start=ReviewActivity.class.getDeclaredField("rangeStart");start.setAccessible(true);start.setInt(reopened,2500);Method fields=ReviewActivity.class.getDeclaredMethod("rangeFields");fields.setAccessible(true);fields.invoke(reopened);require(((TextView)field(reopened,"annotationStatus")).getText().toString().contains("2.000–3.000"),"live overlap identifies saved interval");((Spinner)field(reopened,"label")).setSelection(2);((Button)field(reopened,"confirm")).performClick();return null;});
        SystemClock.sleep(500);saveScreenshot(i,"review-overlap.png");android.view.accessibility.AccessibilityNodeInfo dialog=null;long dialogDeadline=SystemClock.uptimeMillis()+5000;while(SystemClock.uptimeMillis()<dialogDeadline){dialog=i.getUiAutomation().getRootInActiveWindow();if(dialog!=null&&!dialog.findAccessibilityNodeInfosByText("重叠 2.500–3.000 秒").isEmpty())break;SystemClock.sleep(100);}require(dialog!=null&&!dialog.findAccessibilityNodeInfosByText("重叠 2.500–3.000 秒").isEmpty(),"overlap dialog shows exact intersection");require(!dialog.findAccessibilityNodeInfosByText("测试：平移").isEmpty(),"overlap dialog shows saved behavior");saveScreenshot(i,"review-overlap.png");i.sendKeyDownUpSync(KeyEvent.KEYCODE_BACK);i.waitForIdleSync();
        main(i,()->{Method select=ReviewActivity.class.getDeclaredMethod("selectSegment",int.class);select.setAccessible(true);select.invoke(reopened,0);require(((TextView)field(reopened,"annotationStatus")).getText().toString().contains("已标注"),"saved status visible");require(((Button)field(reopened,"confirm")).getText().toString().equals("保存修改"),"editing saved interval has clear action");return null;});
        main(i,()->{Method choose=ReviewActivity.class.getDeclaredMethod("chooseCandidate");choose.setAccessible(true);choose.invoke(reopened);return null;});i.waitForIdleSync();
        SystemClock.sleep(500);saveScreenshot(i,"review-menu.png");
        i.sendKeyDownUpSync(android.view.KeyEvent.KEYCODE_BACK);i.waitForIdleSync();
        main(i,()->{if((boolean)field(reopened,"playing"))((Button)field(reopened,"play")).performClick();android.graphics.Rect bounds=new android.graphics.Rect();require(((Button)field(reopened,"confirm")).getGlobalVisibleRect(bounds),"confirmation visible without scrolling");require(((Spinner)field(reopened,"label")).isShown(),"behavior selector visible");return null;});
        SystemClock.sleep(500);saveScreenshot(i,"review-main.png");
        // Only this uniquely named synthetic session is eligible for later cleanup.
        android.util.Log.i("PawLinkReviewCheck","PASS fixture="+name);
    }
}
