#!/usr/bin/env python3
"""Export a trained Paw Link model as a C++ header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODEL = ROOT / "models" / "cat-behavior-rf.json"
DEFAULT_OUTPUT = ROOT / "firmware" / "self_test" / "model_data.h"


def cpp_float(value: float) -> str:
    text = format(float(value), ".10g")
    if "e" not in text.lower() and "." not in text:
        text += ".0"
    return text + "f"


def float_array(values: list[float], indent: str = "    ") -> str:
    lines = []
    for start in range(0, len(values), 4):
        group = ", ".join(cpp_float(value) for value in values[start : start + 4])
        lines.append(f"{indent}{group},")
    return "\n".join(lines)


def render_centroids(model: dict) -> str:
    labels = model["labels"]
    feature_names = model["feature_names"]
    means = model["feature_mean"]
    scales = model["feature_scale"]
    centroids = model["centroids"]
    width = len(feature_names)

    if len(means) != width or len(scales) != width:
        raise ValueError("model feature arrays have inconsistent lengths")
    if any(len(centroids[label]) != width for label in labels):
        raise ValueError("model centroid arrays have inconsistent lengths")

    label_rows = ", ".join(json.dumps(label) for label in labels)
    centroid_rows = "\n".join(
        "  {\n" + float_array(centroids[label], "      ") + "\n  }," for label in labels
    )
    return f"""// Generated by scripts/export_model.py. Do not edit by hand.
#pragma once

#include <stddef.h>

namespace pawlink_model {{
constexpr size_t kFeatureCount = {width};
constexpr size_t kClassCount = {len(labels)};
constexpr size_t kWindowSamples = {int(model["window_samples"])};

constexpr const char* kLabels[kClassCount] = {{{label_rows}}};

constexpr float kFeatureMean[kFeatureCount] = {{
{float_array(means)}
}};

constexpr float kFeatureScale[kFeatureCount] = {{
{float_array(scales)}
}};

constexpr float kCentroids[kClassCount][kFeatureCount] = {{
{centroid_rows}
}};
}}  // namespace pawlink_model
"""


def render_forest(model: dict) -> str:
    labels = model["labels"]
    trees = model["trees"]
    roots: list[int] = []
    rows: list[str] = []
    offset = 0
    for tree in trees:
        roots.append(offset)
        for feature, threshold, left, right, leaf_class in tree:
            if feature < 0:
                rows.append(f"  {{{cpp_float(threshold)}, 0, 0, 255, {leaf_class}}},")
            else:
                rows.append(
                    f"  {{{cpp_float(threshold)}, {offset + left}, {offset + right}, "
                    f"{feature}, {leaf_class}}},"
                )
        offset += len(tree)
    if offset > 65535:
        raise ValueError("forest exceeds uint16 node index capacity")

    label_rows = ", ".join(json.dumps(label) for label in labels)
    root_rows = ", ".join(str(root) for root in roots)
    return f"""// Generated by scripts/export_model.py. Do not edit by hand.
#pragma once

#include <stddef.h>
#include <stdint.h>

namespace pawlink_model {{
constexpr size_t kFeatureCount = {len(model["feature_names"])};
constexpr size_t kClassCount = {len(labels)};
constexpr size_t kWindowSamples = {int(model["window_samples"])};
constexpr size_t kTreeCount = {len(trees)};
constexpr size_t kNodeCount = {offset};
constexpr uint8_t kLeafFeature = 255;

constexpr const char* kModelType = "random_forest";
constexpr const char* kLabels[kClassCount] = {{{label_rows}}};

struct TreeNode {{
  float threshold;
  uint16_t left;
  uint16_t right;
  uint8_t feature;
  uint8_t leafClass;
}};
static_assert(sizeof(TreeNode) == 12, "unexpected TreeNode layout");

constexpr uint16_t kTreeRoots[kTreeCount] = {{{root_rows}}};
constexpr TreeNode kNodes[kNodeCount] = {{
{chr(10).join(rows)}
}};
}}  // namespace pawlink_model
"""


def render(model: dict) -> str:
    if model.get("model_type") == "random_forest":
        return render_forest(model)
    return render_centroids(model)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the generated header is stale")
    args = parser.parse_args()

    rendered = render(json.loads(args.model.read_text()))
    if args.check:
        if not args.output.exists() or args.output.read_text() != rendered:
            raise SystemExit(f"stale generated model header: {args.output}")
        print(f"model header is current: {args.output}")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"exported {args.model} -> {args.output}")


if __name__ == "__main__":
    main()
